spatial_scope_filter:
  #
  # Filter and sort the metrics according to CORDEX domain
  #
  AUS:
    - Global
    - SH
    - AUS
    - NAU
    - CAU
    - SAU
    - EAU
    - NZ
    - special

  EUR:
    - Global
    - NH
    - EUR
    - MED+NEU+CEU
    - NEU
    - CEU
    - WCE # Western and Central Europe
    - MED
    - NBS # Norwegian and Barents Sea
    - BNS # Baltic and North Sea
    - BAL # Baltic Sea
    - BLK # Black Sea
    - NAtl # Nordic Atlantic
    - SNA # (Southern) North Atlantic
    - special # especial scope (e.g. for resolution or complexity) last

  MED:
    - Global
    - NH
    - EUR
    - MED
    - SNA # (Southern) North Atlantic
    - BLK # Black Sea
    - special

  SEA:
    - Global
    - Tropics
    - Asia
    - SEA
    - NWP # Northwestern Pacific
    - special

lbc_for_source_type:
  default: ARCM
  MED: AORCM

tables_filter:
  #
  # Filters to show in the final summary tables. Must be some of:
  # [filter_avail_and_plausible, filter_avail, filter_plausible, filter_selected, filter_all]
  #
  default:
    - filter_avail_and_plausible
    - filter_avail
    - filter_plausible
    - filter_selected
    - filter_all

  MED:
    - filter_avail_and_plausible
    - filter_avail
    - filter_plausible
    - filter_selected

preferred: # Not implemented
  plausible_values_source: eurocordex_gcm_selection_team
  classes_source: eurocordex_gcm_selection_team
